apiVersion: v1
kind: Service
metadata:
  name: myphpapp-service
spec:
  type: NodePort
  selector:
    app: myphpapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
